### ISSUE TITLE
explain-pause-top doesn't handle closures well (root cause: closure context includes newlines)

### ISSUE THREAD

**Issue by wasamasa** [lastquestion/explain-pause-mode#34]
![20200529_213917](https://user-images.githubusercontent.com/3588994/83298524-e4be7280-a1f4-11ea-9419-a8453e6c38f0.png)

Regular functions are printed fine, closures aren't.  Maybe it's better to abbreviate the display of a function to the max width of a column and add some sign of truncation...

**Comment by lastquestion** [comment]
Oh, no, it should have truncated - if you check the original PR #23 you can see it truncates at the correct width, and then prints the next lines in a new line, truncating as needed. Or it should.

I know what's wrong, it's because the width is incorrectly calculated. This is in windowed mode, you have a gutter on the left that is one character long, it's not being taken into account, the header is one character off too.

I never test in windowed mode. :(

1. Fix the truncation bug
2. Max lines printed should be like, 2, even with truncation. Then there should be an expand option to show the rest. This ties into the UI changes - I think I'll do this when I move the buttons for profiles and stuff into this view from `explain-pauses-profiles`.

**Comment by lastquestion** [comment]
Still, the code should have set `wrap` off, and used truncate on the entire buffer: https://github.com/lastquestion/explain-pause-mode/blob/master/explain-pause-mode.el#L1033

Is it possible you have some configuration or windowed emacs doesn't honor that setting?

Oh, I read more `h v` on `truncate-lines`:

> Note that this is overridden by the variable
‘truncate-partial-width-windows’ if that variable is non-nil
and this buffer is not full-frame width.

So OK, I need to override that too.

**Comment by lastquestion** [comment]
Oh, another realization: make sure scrollbars are accounted for. I never tested that, either.

**Comment by lastquestion** [comment]
Root cause of the specific issue here is because newline was in your actual closure. I will change the command logging to stop logging closure environments as well as lambda bodies.

**Comment by lastquestion** [comment]
But I do think there is still an off by one error in windowed mode, I'll open a new PR for that.
