### ISSUE TITLE
Cannot follow links with mouse click with the mode on

### ISSUE THREAD

**Issue by ThibautVerron** [lastquestion/explain-pause-mode#6]
Hello,

Great mode idea, it should prove very useful !

Just one bug so far: when `explain-pause-mode` is on, clicking on links (be it emacs links such as the ones in help nodes, org links, etc.) does not do anything.

It can be reproduced with `emacs -Q` and loading only dash and the mode.

(tested on Emacs 26.3 on Linux)

**Comment by lastquestion** [comment]
Thanks for the bug report. I'm not surprised, this is 100% because I never use mouse, and there is probably some kind of code I've `advised` on which I didn't account for the arguments correctly and it's dying before the actual callback for the links is being executed.

I would expect there to be some kind of message in the Message buffer, can you check that? If not, I'll try to replicate using terminal mousing first and then if that fails, I guess, yeah, I'll build emacs for macOSX windowing... LOL

**Comment by wasamasa** [comment]
Note that `RET` still works. Most amusingly this renders the links in the buffers the mode creates less useful.

**Comment by lastquestion** [comment]
I got a couple of minutes and pulled down homebrew emacs from cask and replicated this on 26.3 on mac OSX. :+1:

**Comment by lastquestion** [comment]
@wasamasa you can move the point inside the link and `RET` and it works! that's how I do it in terminal-land :-)

**Comment by lastquestion** [comment]
I fixed this and pushed to master in #11 . Can you give it another try?

**Comment by wasamasa** [comment]
This happened to resolve another false positive, with Evil enabled dragging regions with `mouse-1` created reports as long as the mouse dragging took. Now it doesn't do that.

**Comment by ThibautVerron** [comment]
Sorry for the delay, I really thought that I had answered already. Yes it works, thanks!

**Comment by lastquestion** [comment]
Awesome! Thanks both of you for testing :-) I appreciate 💯
