### ISSUE TITLE
Clicking a link in a Circe buffer hits an error in wrap-native

### ISSUE THREAD

**Issue by wasamasa** [lastquestion/explain-pause-mode#84]
Using latest master and clicking on a link with mouse-1 in Circe produced the following:

```
Explain-pause-mode: please report this bug by creating a Github
issue at https://github.com/lastquestion/explain-pause-mode. Explain-pause-mode
is now _disabled_ so you can continue to hopefully use Emacs. Info follows:

explain-pause version: 0.1
emacs version: 26.3

not top level in wrap-native for #<subr read-event>
current
#s(explain-pause-command-record root-emacs nil nil 39800287 (24343 20953 94813 977000) nil nil nil nil 0)

Backtrace:
  (explain-pause-report-measuring-bug "not top level in wrap-native for #<subr read-event>" "current" #s(explain-pause-command-record root-emacs nil nil 39800287 (24343 20953 94813 977000) nil nil nil nil 0))
  (explain-pause--wrap-native #<subr read-event> nil t 0.45)
  (apply explain-pause--wrap-native #<subr read-event> (nil t 0.45))
  (read-event nil t 0.45)
  (sit-for 0.45)
  (mouse--down-1-maybe-follows-link nil)
```

**Comment by lastquestion** [comment]
Hi so sorry I have been busy with some other projects the last few days. :'(

Hm, the `mouse--down-1-maybe-follows-link` should have come from a keymapping so it should have been called via `call-interactively`, or at least, that's what I assumed when I first glanced over the key map / mouse code. 

I just clicked a link and generated a backtrace in emacs 26.3, it appears that `mouse--down-1-maybe-follows-link` is just magically called somehow. I will dig into it, I will guess that maybe special event keys are magically called outside without `call-interactively`?!

**Comment by lastquestion** [comment]
Ahhhah, I understand now.

`mouse.el` defines `#'mouse--down-1-maybe-follows-link` into `key-translation-map`.... but the `key-translation-map` is special! It is handled specially in `keyboard.c`.

`read_key_sequence` -> `keyremap_step` -> `access_keymap_keyremap` -> if the map entry is a function, call it:

https://github.com/emacs-mirror/emacs/blob/master/src/keyboard.c#L9164 via `call1`, which means the value must be a `functionp`. So that could be a symbol with a function value, a lambda, a compiled lambda, etc.

This applies to the special keymaps `key-translation-map`, `input-decode-map`, `local-function-key-map` -> `function-key-map`.

OK, I will wrap these just like the special hook lists. Basically, during keyboard input, these special keyboard maps might run functions that can do things, including... for example... `sit-for`. Which kind of feels strange at first but then makes sense, if you want to wait to see if the user does something that ought to be "combined", then a `sit-for` makes sense...

**Comment by lastquestion** [comment]
Notes: `define_keys` is called in `term.c` for `Vinput_decode_map`, as part of `init_tty`. `input-decode-map` is terminal local.

**Comment by lastquestion** [comment]
The implementation completely changed in emacs 27, and doesn't use a `sit-for` anymore. That explains why I didn't notice this during manual testing. 😢 

https://github.com/emacs-mirror/emacs/commit/3d5e31eceb9dc1fb62b2b27bcab549df3bd04ce9

**Comment by lastquestion** [comment]
OK, it took me a while but I have finally fixed this. I have tested clicking on emacs 26, in various frame combinations, using `server.el`, creating GUI and TTY frames. So sorry it took a while to fix, let me know if it doesn't work 💯

**Comment by wasamasa** [comment]
Thanks, that seems to have done the trick.
